### ISSUE TITLE
npm packages.

### ISSUE THREAD

**Issue by 0nza1101** [landru29/leaflet-velocity-ts#1]
Can you please create an npm package for better implementation. In that case I can update my repo to your leaflet-velocity version which seems better, especially in resizing particles when zooming and moving the map.

**Comment by landru29** [comment]
Yes, i'm xorking on it. But comparing to your repo, there is a regression: I do not display speed values on the map when the mouse is over a region

**Comment by landru29** [comment]
(Sorry) I mean comparing to repo leaflet-volecity that is already on npm

**Comment by 0nza1101** [comment]
I just made a pull request with that feature implemented, now your version remains the same as leaflet velocity without laggy particles effect when zooming and moving the map 👍  .
